### PR TITLE
6428 persona additional fields

### PR DESCRIPTION
**Pull request by ethteck**

### CODE REVIEW

**Comment by ethteck** [comment]
I'm not sure the codacy issue is an issue, because no arg here would use the system's locale if I remember correctly. This is the desired behavior anyway.

**Comment by rcordovano** [comment]
@ethteck, agreed about the Codacy issue.

**Comment by rcordovano** [comment]
Please resolve the merge conflict, thanks.

**Comment by ethteck** [comment]
All set @rcordovano

**Pull request merged**
