### PR TITLE
5565 Add support for webp image files

### PR DESCRIPTION
**Pull request by markmckinnon**
Add new library to support webp format and add supported file mime types of image/webp

### CODE REVIEW

**Comment by esaunders** [comment]
Is there a reason why the JAR file needs to be checked into thirdparty? It looks like it can be downloaded at build time through ivy/maven.
https://mvnrepository.com/artifact/org.sejda.webp-imageio/webp-imageio-sejda/0.1.0

**Comment by esaunders** [comment]
After getting the JAR using Ivy you still need the step (that you had previously) of adding it as a wrapped jar to the Autopsy-Core project.

**Comment by esaunders** [comment]
I know this wasn't explicitly called out in the original story but I would think that (a) we want the webp files to appear in the results table under Views -> File Types -> By Extension -> Images and (b) the icon for these files in the results table should be the same as is used for jpeg and tif (but not gif apparently).

**Comment by markmckinnon** [comment]
Will make above changes

**Comment by markmckinnon** [comment]
Everything should be all set now.

**Comment by esaunders** [comment]
Cool, I'll check it out now. Can you remove the Bundle.properties from the PR...I don't believe it is necessary? Thanks.

**Comment by markmckinnon** [comment]
I put in the old copy of the bundle.properties so it should have removed it from the PR as a file changed.  I just checked the files and do not see that as a file that was changed now.  Unless I am looking at something wrong.

**Comment by esaunders** [comment]
Ok, I'm not seeing it now. Don't know what it was showing me earlier.

**Pull request merged**
