### PR TITLE
6048 remove hard coded font sizes

### PR DESCRIPTION
**Pull request by wschaeferB**

### CODE REVIEW

**Comment by rcordovano** [comment]
@wschaeferB, this story will not auto-merge. Please resolve the merge conflicts, thanks!

**Comment by wschaeferB** [comment]
alright should be ok now

**Comment by wschaeferB** [comment]
I know there are new merge conflicts here but this is going to keep happening with basically every PR that has changes to a form or auto generated UI code. So I want to know if I need to fix them as they crop up  or can fix them bulk when this is closer to approval?

**Comment by rcordovano** [comment]
We can resolve merge conflicts later.

**Pull request merged**
