### PR TITLE
5165 logical imager dsp to support multiple drives

### PR DESCRIPTION
**Pull request by jkho**

### CODE REVIEW

**Comment by APriestman** [comment]
Please address the codacy complaints

**Comment by APriestman** [comment]
You've included a lot of Bundle.properties-MERGED files that are unrelated to your changes.

**Comment by jkho** [comment]
I'll resubmit with just my changes, after fixing Codacy errors.

**Comment by jkho** [comment]
@APriestman When I resolved the 2 conflict files by merging release-4.12.0 into my branch, it generates all these extra files that has nothing to do with my changes. I don't know how to fix this.
At least my branch is sync-ed up to the release-4.12.0 branch for the PR.

**Comment by APriestman** [comment]
There are still a number of Bundle.properties-MERGED files that don't belong in this PR

**Comment by jkho** [comment]
Fixing it now...

**Comment by jkho** [comment]
Down to 6 files changed.

**Pull request merged**
