### PR TITLE
8425 snap

### PR DESCRIPTION
**Pull request by gdicristofaro**

### CODE REVIEW

**Comment by miguel-negrao** [comment]
Is there a plan to start releasing Autopsy also as a snap ?

**Review by markmckinnon — APPROVED** [review]

**Comment by gdicristofaro** [comment]
> Is there a plan to start releasing Autopsy also as a snap ?

Hi @miguel-negrao , sorry for the delay in response.  Yes, the plan is to have a snap package in the next release.

**Comment by miguel-negrao** [comment]
Hi @gdicristofaro The new version of autopsy, 4.21, came out 2 days ago, but I can't find the snap. Are you going to release a snap version for 4.21 ? It would be really nice to have an easier way to install on Linux. Thanks !

**Comment by gdicristofaro** [comment]
> Hi @gdicristofaro The new version of autopsy, 4.21, came out 2 days ago, but I can't find the snap. Are you going to release a snap version for 4.21 ? It would be really nice to have an easier way to install on Linux. Thanks !

Hi @miguel-negrao , the snap package should be in the [Autopsy 4.21.0 release](https://github.com/sleuthkit/autopsy/releases/tag/autopsy-4.21.0) now.  There are some notes [here](https://github.com/sleuthkit/autopsy/tree/develop/snap) about getting started.  Thanks for your interest!

**Comment by miguel-negrao** [comment]
I've tried the snap and so far everything seems to work. I had to run `snap connections autopsy | sed -nE 's/^[^ ]* *([^ ]*) *- *- *$/\1/p' | xargs -I{} sudo snap connect {}` to get anything to work. I'll report if anything is not working.

**Pull request merged**
