### PR TITLE
5732 implement xry report validation

### PR DESCRIPTION
**Pull request by dannysmyda**

### CODE REVIEW

**Comment by dannysmyda** [comment]
I would ignore Codacy for the time being. These classes will be extended in later stories to contain other non-static methods.

**Comment by rcordovano** [comment]
Actually, there is an issue I messed, but Codacy did not. The utility classes need private constructors. I don't care about the naming rules violated. We need to suppress them at some point.

**Comment by dannysmyda** [comment]
@rcordovano These classes were never intended to be utility classes. It just so happens that this portion of the design is utility-esque. I'd rather group these methods with their relevant classes than have them floating off somewhere non-obvious.

**Comment by rcordovano** [comment]
Sounds good. Please resolve the merge conflict and I will merge.

**Comment by dannysmyda** [comment]
> Sounds good. Please resolve the merge conflict and I will merge.

Done.

**Pull request merged**
