### PR TITLE
7340 file in dir action

### PR DESCRIPTION
**Pull request by gdicristofaro**

### CODE REVIEW

**Review by wschaeferB — CHANGES_REQUESTED** [review]
See Jira for change requested.

**Comment by gdicristofaro** [comment]
> See Jira for change requested.

Ok.  Should be done.

**Review by wschaeferB — APPROVED** [review]

**Comment by rcordovano** [comment]
@gdicristofaro, please address the merge conflicts, thanks!

**Comment by gdicristofaro** [comment]
> @gdicristofaro, please address the merge conflicts, thanks!

Ok.  Should be done now.

**Pull request merged**
